apiVersion: v1
kind: Service
metadata:
  name: postgres-master-headless
  namespace: medical-rag
spec:
  clusterIP: None
  selector:
    app: postgres-master
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
