apiVersion: v1
kind: Service
metadata:
  name: postgres-slave
  namespace: medical-rag
spec:
  selector:
    app: postgres-slave
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
