apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: medical-rag
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
