apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: medical-rag
type: Opaque
stringData:
  # Demo credentials for reviewer flow:
  # username: reviewer
  # password: reviewer
  #
  # The ingress-nginx basic auth example expects the key to be named `auth`.
  auth: reviewer:$apr1$1ygVepg/$1S/DMq63ZWBfRFIp5bCUu1
